# Setup
title: TheKey.tk
description: Where morbid curiosity is key
url: https://www.the-key.tk
id: https://www.the-key.tk
baseurl: ""
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-admin
  - jekyll-feed

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-193334062-1

# Specify the author for blog posts
author:
  name: TheKey
  url: https://www.the-key.tk
  twitter: IHaveNoTwitter

# Custom vars
version: 3.0.0

# Navbar page list
nav:

  - title: About
    url: /about
